{
 "title": "NAFFTrack",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": "discord-bot" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Python version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (implementation, version) (python_info{job=\"$job\"})",
     "legendFormat": "{{implementation}} {{version}}"
    }
   ]
  },
  {
   "title": "Library version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_info{job=\"$job\"}",
     "legendFormat": "naff {{version}}"
    }
   ]
  },
  {
   "title": "Logged in as",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_bot_info{job=\"$job\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Guilds amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "guilds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_guilds{job=\"$job\"}",
     "legendFormat": "Guilds"
    }
   ]
  },
  {
   "title": "Guilds",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "guilds" } },
   "targets": [
    {
     "expr": "naff_guilds{job=\"$job\"}",
     "legendFormat": "Guilds amount"
    }
   ]
  },
  {
   "title": "Websocket latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(naff_bot_latency{job=\"$job\"}[$__interval]) > 0",
     "legendFormat": "Average latency over 5 minutes"
    },
    {
     "expr": "naff_bot_latency{job=\"$job\"} > 0",
     "legendFormat": "Actual latency"
    }
   ]
  },
  {
   "title": "Guilds per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "increase(naff_guilds{job=\"$job\"}[1d])"
    }
   ]
  },
  {
   "title": "Interactions Registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_interactions_registered{job=\"$job\"}",
     "legendFormat": "Interactions"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages recieved total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Messages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(naff_received_messages_total{job=\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Recieved messages by guild",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Messages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(topk(10, increase(naff_received_messages_total{job=\"$job\"}[$__range])>0), \"guild_name\", \"<DM>\", \"dm\", \"1\")",
     "legendFormat": "{{guild_name}}"
    }
   ]
  },
  {
   "title": "Messages recieved",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(topk(10, increase(naff_received_messages_total{job=\"$job\"}[$__interval])>0), \"guild_name\", \"<DM>\", \"dm\", \"1\")",
     "legendFormat": "{{guild_name}}"
    },
    {
     "expr": "sum(increase(naff_received_messages_total{job=\"$job\"}[$__interval]))>0",
     "legendFormat": "<TOTAL>"
    }
   ]
  },
  {
   "title": "Messages per guild",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Messages" } },
   "targets": [
    {
     "expr": "label_replace(topk(10, increase(naff_received_messages_total{job=\"$job\"}[$__range])), \"guild_name\", \"<DM>\", \"dm\", \"1\") > 0",
     "legendFormat": "{{guild_name}}"
    },
    {
     "expr": "sum(increase(naff_received_messages_total{job=\"$job\"}[$__range]))",
     "legendFormat": "<TOTAL>"
    }
   ]
  },
  { "title": "Slash commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Command execution time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(naff_slash_command_perf_bucket{job=\"$job\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Commands executed",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "label_replace(topk(10, sum(increase(naff_slash_command_perf_count{job=\"$job\"}[$__interval])>0) by (guild_name)), \"guild_name\", \"<DM>\", \"dm\", \"1\")",
     "legendFormat": "{{guild_name}}"
    },
    {
     "expr": "sum(increase(naff_slash_command_perf_count{job=\"$job\"}[$__interval]))>0",
     "legendFormat": "<TOTAL>"
    }
   ]
  },
  {
   "title": "Popular Commands",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(label_replace(sum by(base_name, group_name, command_name) (label_replace(increase(naff_slash_command_perf_count{job=\"$job\"}[$__range]), \"group_name\", \"\", \"group_name\", \"None\")), \"command_name\", \"\", \"command_name\", \"None\")) > 0)",
     "legendFormat": "{{base_name}} {{group_name}} {{command_name}}"
    }
   ]
  }
 ]
}